import turtle

turtle.pencolor('red')
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)

turtle.penup()
turtle.goto(300, 0)
turtle.pendown()
turtle.pencolor('green')
turtle.right(120)
turtle.forward(80)
turtle.right(120)
turtle.forward(80)
turtle.right(120)
turtle.forward(80)

turtle.pencolor('blue')
turtle.penup()
turtle.goto(600, 0)
turtle.pendown()
turtle.left(90)
turtle.forward(80)
turtle.left(85)
turtle.forward(80)
turtle.left(85)
turtle.forward(80)
turtle.left(85)
turtle.forward(80)
turtle.left(85)
turtle.forward(80)

turtle.done()